import * as React from 'react'

// ** MUI Imports
import Grid from '@mui/material/Grid'

import { Typography } from '@mui/material'

import LiveClassItems from 'src/layouts/components/LiveClasses/LiveClassesItem'

// ** MUI Imports
import DialogForm from './DialogForm'
import { StudentListID } from 'src/pages/classes'
import useAuth from 'src/@core/hooks/useAuth'
import useAxios from 'src/@core/hooks/useAxios'
import { useEffect } from 'react'
import moment from 'moment'
import FilterClass from '../Filter/FilterClass'
import ClassForAdmin from '../ClassForAdmin'

export interface NewClassModel {
  className: string
  dayStudy: string[]
  startTime: string
  endTime: string
  studentListId: StudentListID[]
  dateStartClass: string
  subjectId: string
  AppUserId: string
  classRoomID: string
  teacherId: string
}

const API_GET_STUDENT_BY_ID = '/api/v1/student/get-student-by-appuser-id/'
const API_GET_CLASS_TEACHER = '/api/v1/teacher/get-schedule-of-teacher'
const API_GET_CLASS_STUDENT = '/api/v1/student/get-schedule-of-student-by-student-id'
const API_GET_ALL_CLASS_NOT_FINISHED = '/api/v1/classes/get-all-classes-are-not-finshed'

export interface ClassModel {
  className: string
  classroomName: string
  dayStudy: string
  startTime: string
  endTime: string
  timeDetail: string
  totalStudentInClass: number
  classWasCheckedAttendant: boolean
}

export type ObjectFilterClass = {
  AppUserId: string
  DateStartOfWeek: string
  DateEndOfWeek: string
}

// Generated by https://quicktype.io

export interface ClassForAdminModel {
  className: string
  dayStudy: string[]
  startTime: string
  endTime: string
  totalStudentInClass: number
  subjectId: string
  subjectName: string
  teacherId: string
  appUserTeacherId: string
  teacherName: string
}

// Generated by https://quicktype.io

export interface StudentInfoModel {
  appUserId: string
  studentId: string
  parent: Parent
  userName: string
  fullName: string
  email: string
  phoneNumber: string
  dateOfBirth: string
  gender: string
  address: string
  photoUrl: string
}

export interface Parent {
  parentId: string
  userName: string
  fullName: string
  email: string
  phoneNumber: string
  dateOfBirth: string
  gender: string
  address: string
  photoUrl: string
}

export default function NewClassFormLiveClass() {
  const [startDate, setStartDate] = React.useState<string>(moment().startOf('week').toISOString())
  const [endDate, setEndDate] = React.useState<string>(moment().endOf('week').toISOString())

  const [classes, setClasses] = React.useState<ClassModel[]>([])
  const [classForAdmin, setClassForAdmin] = React.useState<ClassForAdminModel[]>([])
  const axiosClient = useAxios()

  const authen = useAuth()
  const id = authen.Id
  const role = authen.role

  const isAdmin = () => role === 'Admin'
  const isTeacher = () => role === 'Teacher'

  useEffect(() => {
    const fetchClasses = async () => {
      try {
        if (!id) return

        const response = await axiosClient.call('get', API_GET_CLASS_TEACHER, {
          DateEndOfWeek: !!endDate ? moment(endDate).format('YYYY-MM-DD') : moment().endOf('week').format('YYYY-MM-DD'),
          DateStartOfWeek: !!startDate
            ? moment(startDate).format('YYYY-MM-DD')
            : moment().startOf('week').format('YYYY-MM-DD'),
          AppUserId: id
        } as ObjectFilterClass)

        setClasses(response as ClassModel[])
      } catch (error) {
        console.log('Not found table time' + error)
      }
    }

    const fetchAllClassNotFinished = async () => {
      try {
        const response = await axiosClient.call('get', API_GET_ALL_CLASS_NOT_FINISHED, null, true)

        setClassForAdmin(response as ClassForAdminModel[])
      } catch (error) {
        console.log('Not found table time' + error)
      }
    }

    const fetchStudentInfo = async () => {
      try {
        const response = await axiosClient.call('get', API_GET_STUDENT_BY_ID + id, null, true)

        return (response as StudentInfoModel).studentId
      } catch (error) {}
    }

    const fetchStudentClass = async () => {
      try {
        if (!id) return
        const studentId = await fetchStudentInfo()
        const response = await axiosClient.call('get', API_GET_CLASS_STUDENT, {
          StudentId: studentId
        })

        setClasses(response as ClassModel[])
      } catch (error) {
        console.log('Not found table time' + error)
      }
    }

    if (isAdmin()) {
      fetchAllClassNotFinished()
    } else if (isTeacher()) {
      fetchClasses()
    } else {
      fetchStudentClass()
    }
  }, [id, endDate, startDate])

  return (
    <Grid container direction={'row'} spacing={4}>
      {!isAdmin() && (
        <FilterClass startDate={startDate} endDate={endDate} setEndDate={setEndDate} setStartDate={setStartDate} />
      )}
      <Grid
        item
        display={'flex'}
        flexWrap={'wrap'}
        justifyContent={'space-between'}
        width={'100%'}
        alignItems={'center'}
      >
        <Typography sx={{ color: 'black', fontWeight: 'bold', fontSize: '20px' }}> Live Classes</Typography>
        {role === 'Admin' && <DialogForm></DialogForm>}
      </Grid>

      {classes.map((item, index) => (
        <Grid item xl={3} lg={3} md={3} xs={6} sm={6} key={index}>
          <LiveClassItems data={item}></LiveClassItems>
        </Grid>
      ))}
      {classForAdmin.map((item, index) => (
        <Grid item xl={3} lg={3} md={3} xs={6} sm={6} key={index}>
          <ClassForAdmin data={item}></ClassForAdmin>
        </Grid>
      ))}
    </Grid>
  )
}
