import { Box, Button, Grid, Typography } from '@mui/material'
import { Calendar, ClockOutline } from 'mdi-material-ui'
import * as React from 'react'
import AttendanceTableStudent from './AttendanceTableStudent'
import { ClassModel } from '../AddNewClass/NewClassFormLiveClass'
import moment from 'moment'
import { StudentModel } from '../HistoryClasses'
import useAxios from 'src/@core/hooks/useAxios'
import { toast } from 'react-toastify'

// function createData(StudentID: string, StudentName: string, Class: string, Attendance: string, isAttendance: boolean) {
//   return { StudentID, StudentName, Class, Attendance, isAttendance } as Student
// }

// const rows = [
//   createData('SE150627', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150628', 'Nguyễn Thành Nhân', 'C#', 'Absent', false),
//   createData('SE150629', 'Nguyễn Ngọc Thái Vĩ', 'C#', 'Absent', false),
//   createData('SE150630', 'Nguyễn Thanh Duy', 'C#', 'Absent', false),
//   createData('SE150631', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150632', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150633', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150634', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150635', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150636', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150637', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150638', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150639', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150640', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150641', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150642', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false),
//   createData('SE150643', 'Trần Thiện Quốc Anh', 'C#', 'Absent', false)
// ]

// export type Student = {
//   StudentID: string
//   StudentName: string
//   Class: string
//   Attendance: string
//   isAttendance?: boolean
// }

// Generated by https://quicktype.io

export interface ObjectRequestCheckAttendenceModel {
  dateStudy: string
  className: string
  startTime: string
  endTime: string
  studentName: string
  studentId: string
  attendanceStatus: number
  attendanceId: string
}

interface AttendanceReportDrawerProps {
  classData: ClassModel
  studentList: StudentModel[]
  handleCheckAttendance: (studentId: string) => void
}

const API_CHECK_ATTENDANCE = '/api/v1/attendances'

export default function AttendanceReportDrawer({
  classData,
  studentList,
  handleCheckAttendance
}: AttendanceReportDrawerProps) {
  const axiosClient = useAxios()

  const handleSubmit = async () => {
    try {
      const payload: ObjectRequestCheckAttendenceModel[] = studentList.map(student => {
        return {
          ...classData,
          ...student
        } as ObjectRequestCheckAttendenceModel
      })

      console.table(payload)

      const response = await axiosClient.call('post', API_CHECK_ATTENDANCE, payload)

      console.log(response)
      toast.success('Check attendance successfully !!!')
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <Grid container width='750px' padding={'10px'}>
      <Grid
        item
        display={'flex'}
        justifyContent={'space-between'}
        width={'100%'}
        alignItems={'center'}
        sx={{ paddingBottom: '20px' }}
      >
        <Typography sx={{ color: '#4B4453', fontWeight: 'bold', fontSize: '23px' }}>Attendance Report</Typography>
        <Button
          sx={{
            backgroundColor: '#C4FCEF',
            color: '#50bf62',
            fontWeight: 'bold',
            fontSize: '13px',
            ':hover': {
              color: 'white',
              backgroundColor: '#0081CF'
            }
          }}
          onClick={handleSubmit}
        >
          Submit attendance
        </Button>
      </Grid>
      <Grid item paddingBottom={'20px'} xl={12} lg={12} md={12} width={'100%'}>
        <Typography sx={{ color: 'black', fontWeight: 'bold', fontSize: '18px', width: '100%' }}>
          {classData.className}
        </Typography>
      </Grid>

      <Grid item sx={{ display: 'flex', flexDirection: 'row', gap: '20px', width: '100%' }} paddingBottom={'20px'}>
        {/* <Typography
          sx={{
            border: '1px solid #B0AAAE',
            borderRadius: '10px',
            width: 'fit-content',
            padding: '5px',
            fontSize: '12px',
            fontWeight: 'bold'
          }}
        >
          Teacher: Ngô Thị Hương
        </Typography> */}
        <Box sx={{ display: 'flex', flexDirection: 'row' }}>
          <ClockOutline></ClockOutline>
          <Typography sx={{ marginRight: '15px' }}>
            {moment(classData.startTime, 'HH:mm:ss').format('HH:mm')}
          </Typography>
          <Calendar></Calendar>
          <Typography>{classData.dayStudy}</Typography>
        </Box>
        <Typography
          sx={{
            border: '1px solid #CECFD7',
            borderRadius: '10px',
            width: 'fit-content',
            padding: '5px',
            fontSize: '12px',
            fontWeight: 'bold',
            backgroundColor: '#BCECC4',
            color: '#40C053'
          }}
        >
          Status: Complete
        </Typography>
      </Grid>

      <Grid item>
        <AttendanceTableStudent students={studentList} handleCheckAttendance={handleCheckAttendance} />
      </Grid>
    </Grid>
  )
}
